services:
  - type: web
    name: codemaster-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    rootDir: backend
    envVars:
      - key: JUDGE0_API_URL
        sync: false
      - key: JUDGE0_API_KEY
        sync: false
      - key: JUDGE0_HOST
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        sync: false
      - key: GROQ_API_URL
        sync: false